routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return view('welcome');
});

Route::get('admin/login', ['middleware' => 'guest', function () {
    return view('auth.login');
}])->name('admin.login');

Auth::routes();

/* Front Routes */
Route::group(['namespace' => 'Front', 'middleware' => ['auth']], function () {
	Route::get('/home', 'PageController@index')->name('front.home');
});
/* ************************* */
Route::get('/admin', function () {
	return Redirect::route('admin.login');
});

Route::group(['namespace' => 'Admin', 'prefix' => 'admin', 'middleware' => ['auth', 'role:admin']], function () {

	Route::get('/home', 'HomeController@index')->name('home');

	/* Users */
		Route::get('/users/data', 'UserController@data')->name('users.data');
		Route::match(['get', 'post'], '/users/userdocument', 'UserController@userdocument')->name('users.userdocument');
		Route::post('/users/download', 'UserController@getDownload')->name('users.getDownload');
		Route::match(['get', 'patch'], '/users/{user}/change_pass', 'UserController@changePass')->name('users.change_pass');
		Route::resource('users', 'UserController');
	/* ********************** */

	/* Permissions */
		Route::get('/permissions/data', 'PermissionController@data')->name('permissions.data');
		Route::get('/permissions/get_actions/{controller}', 'PermissionController@getControllerActions')->name('permissions.get_actions');
		Route::resource('permissions', 'PermissionController', ['except' => ['show']]);
	/* ********************** */

	/* Roles */
		Route::get('/roles/data', 'RoleController@data')->name('roles.data');
		Route::resource('roles', 'RoleController');
	/* ********************** */

	/* Options */
		Route::get('/options/data', 'OptionController@data')->name('options.data');
		Route::resource('options', 'OptionController', ['except' => ['show', 'destroy']]);
	/* ********************** */
});

resources/views/partials/footer.blade.php
<!-- /.content-wrapper -->
<footer class="main-footer">
	<strong>Copyright &copy; {{ date('Y', time()) }}</strong>
</footer>

resources/views/partials/header.blade.php
  <header class="main-header">
    <!-- Logo -->
    <a href="{{ route('home') }}" class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini"><b>D</b></span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg"><b>{{ config('app.name') }}</b></span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
      <!-- Sidebar toggle button-->
      <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
        <span class="sr-only">Toggle navigation</span>
      </a>

      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
          <!-- User Account: style can be found in dropdown.less -->
          <li class="dropdown user user-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <img src="{{ (!empty(Auth::user()->profile_image))?url(Auth::user()->profile_image):url('/assets/img').'/default-user.png' }}" class="user-image" alt="User Image">
              <span class="hidden-xs">{{ ucwords(Auth::user()->name) }}</span>
            </a>
            <ul class="dropdown-menu">
              <!-- User image -->
              <li class="user-header">
                <img src="{{ (!empty(Auth::user()->profile_image))?url(Auth::user()->profile_image):url('/assets/img').'/default-user.png' }}" class="img-circle" alt="User Image">
                <p>
                  {{ ucwords(Auth::user()->name) }}
                  <small>Member since {{ date('M Y', strtotime(Auth::user()->created_at)) }}</small>
                </p>
              </li>
              <!-- Menu Footer-->
              <li class="user-footer">
                <div class="pull-left">
                  <a href="{{ route('users.edit', Auth::user()->id) }}" class="btn btn-default btn-flat">Profile</a>
                </div>
                <div class="pull-right">
                  <a href="{{ url('/logout') }}" class="btn btn-default btn-flat" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">Sign out</a>
                  <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
                      {{ csrf_field() }}
                  </form>
                </div>
              </li>
            </ul>
          </li>
        </ul>
      </div>
    </nav>
  </header>

resources/views/partials/modal.blade.php
<!-- Modal -->
<div class="modal fade" id="empty_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Loading</h4>
            </div>
            <div class="modal-body" id="append_modal_form">
                
            </div>
        </div>
    </div>
</div>

<div class="modal_loader_template" style="display:none;">
    <div class="text-center loader">
        <i class="fa fa-circle-o-notch fa-spin fa-3x" style="color:#8e8e8e;" aria-hidden="true"></i>
    </div>    
</div>

resources/views/partials/sidebar.blade.php
  <!-- Left side column. contains the logo and sidebar -->
  <aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
      <!-- Sidebar user panel -->
      <div class="user-panel">
        <div class="pull-left image">
          <img src="{{ (!empty(Auth::user()->profile_image))?url(Auth::user()->profile_image):url('/assets/img').'/default-user.png' }}" class="img-circle" alt="User Image">
        </div>
        <div class="pull-left info">
          <p>{{ ucwords(Auth::user()->name) }}</p>
        </div>
      </div>
      <!-- sidebar menu: : style can be found in sidebar.less -->
      <ul class="sidebar-menu">
        <li class="header">MAIN NAVIGATION</li>
        <li><a href="{{ route('home') }}"><i class="fa fa-dashboard"></i> <span>Dashboard</span></a></li>
        @ability('admin', 'create_user,list_user')
        <li class="treeview">
          <a href="#">
            <i class="fa fa-users"></i> <span>Users</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            @ability('admin', 'create_user')
              <li><a href="{{ route('users.index') }}"><i class="fa fa-list"></i> List Users</a></li>
            @endability
            @ability('admin', 'list_user')
              <li><a href="{{ route('users.create') }}"><i class="fa fa-plus"></i> Create User</a></li>
            @endability
          </ul>
        </li>
        @endability

        <li class="treeview">
          <a href="#">
            <i class="fa fa-database"></i> <span>Masters</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li class="treeview">
              <a href="#">
                <i class="fa fa-cubes"></i> <span>Options</span>
                <span class="pull-right-container">
                  <i class="fa fa-angle-left pull-right"></i>
                </span>
              </a>
              <ul class="treeview-menu">
                <li><a href="{{ route('options.index') }}"><i class="fa fa-list"></i> List Option</a></li>
                <li><a href="{{ route('options.create') }}"><i class="fa fa-plus"></i> Create Option</a></li>
              </ul>
            </li>
          </ul>
        </li>

        <li class="treeview">
          <a href="#">
            <i class="fa fa-cogs"></i> <span>Settings</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          @ability('admin', 'manage_roles_and_permissions')
          <ul class="treeview-menu">
            <li class="treeview">
              <a href="#">
                <i class="fa fa-user-secret"></i> <span>Roles</span>
                <span class="pull-right-container">
                  <i class="fa fa-angle-left pull-right"></i>
                </span>
              </a>
              <ul class="treeview-menu">
                <li><a href="{{ route('roles.index') }}"><i class="fa fa-list"></i> List Roles</a></li>
                <li><a href="{{ route('roles.create') }}"><i class="fa fa-plus"></i> Create Role</a></li>
              </ul>
            </li>

            <li class="treeview">
              <a href="#">
                <i class="fa fa-lock"></i> <span>Permissions</span>
                <span class="pull-right-container">
                  <i class="fa fa-angle-left pull-right"></i>
                </span>
              </a>
              <ul class="treeview-menu">
                <li><a href="{{ route('permissions.index') }}"><i class="fa fa-list"></i> List Permissions</a></li>
                <li><a href="{{ route('permissions.create') }}"><i class="fa fa-plus"></i> Create Permission</a></li>
              </ul>
            </li>
          </ul>
          @endability
        </li>

        <li class="header">ACTIONS</li>

        <li class="treeview">
          <a href="{{ url('/logout') }}"  onclick="event.preventDefault(); document.getElementById('logout-form-siderbar').submit();">
            <i class="fa fa-sign-out text-red"></i> <span>Logout</span>
            <span class="pull-right-container">
          </a>
          
          <form id="logout-form-siderbar" action="{{ url('/logout') }}" method="POST" style="display: none;">
             {{ csrf_field() }}
          </form>
        </li>
      </ul>
    </section>
    <!-- /.sidebar -->
  </aside>